/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SystemMonitoringRouteImport } from './routes/system-monitoring'
import { Route as SignalAdjustmentRouteImport } from './routes/signal-adjustment'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as MachinesRouteImport } from './routes/machines'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AutoHmiRouteImport } from './routes/auto-hmi'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as AlertsRouteImport } from './routes/alerts'
import { Route as IndexRouteImport } from './routes/index'

const SystemMonitoringRoute = SystemMonitoringRouteImport.update({
  id: '/system-monitoring',
  path: '/system-monitoring',
  getParentRoute: () => rootRouteImport,
} as any)
const SignalAdjustmentRoute = SignalAdjustmentRouteImport.update({
  id: '/signal-adjustment',
  path: '/signal-adjustment',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const MachinesRoute = MachinesRouteImport.update({
  id: '/machines',
  path: '/machines',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AutoHmiRoute = AutoHmiRouteImport.update({
  id: '/auto-hmi',
  path: '/auto-hmi',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const AlertsRoute = AlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/alerts': typeof AlertsRoute
  '/analytics': typeof AnalyticsRoute
  '/auto-hmi': typeof AutoHmiRoute
  '/login': typeof LoginRoute
  '/machines': typeof MachinesRoute
  '/settings': typeof SettingsRoute
  '/signal-adjustment': typeof SignalAdjustmentRoute
  '/system-monitoring': typeof SystemMonitoringRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/alerts': typeof AlertsRoute
  '/analytics': typeof AnalyticsRoute
  '/auto-hmi': typeof AutoHmiRoute
  '/login': typeof LoginRoute
  '/machines': typeof MachinesRoute
  '/settings': typeof SettingsRoute
  '/signal-adjustment': typeof SignalAdjustmentRoute
  '/system-monitoring': typeof SystemMonitoringRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/alerts': typeof AlertsRoute
  '/analytics': typeof AnalyticsRoute
  '/auto-hmi': typeof AutoHmiRoute
  '/login': typeof LoginRoute
  '/machines': typeof MachinesRoute
  '/settings': typeof SettingsRoute
  '/signal-adjustment': typeof SignalAdjustmentRoute
  '/system-monitoring': typeof SystemMonitoringRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/alerts'
    | '/analytics'
    | '/auto-hmi'
    | '/login'
    | '/machines'
    | '/settings'
    | '/signal-adjustment'
    | '/system-monitoring'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/alerts'
    | '/analytics'
    | '/auto-hmi'
    | '/login'
    | '/machines'
    | '/settings'
    | '/signal-adjustment'
    | '/system-monitoring'
  id:
    | '__root__'
    | '/'
    | '/alerts'
    | '/analytics'
    | '/auto-hmi'
    | '/login'
    | '/machines'
    | '/settings'
    | '/signal-adjustment'
    | '/system-monitoring'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AlertsRoute: typeof AlertsRoute
  AnalyticsRoute: typeof AnalyticsRoute
  AutoHmiRoute: typeof AutoHmiRoute
  LoginRoute: typeof LoginRoute
  MachinesRoute: typeof MachinesRoute
  SettingsRoute: typeof SettingsRoute
  SignalAdjustmentRoute: typeof SignalAdjustmentRoute
  SystemMonitoringRoute: typeof SystemMonitoringRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/system-monitoring': {
      id: '/system-monitoring'
      path: '/system-monitoring'
      fullPath: '/system-monitoring'
      preLoaderRoute: typeof SystemMonitoringRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signal-adjustment': {
      id: '/signal-adjustment'
      path: '/signal-adjustment'
      fullPath: '/signal-adjustment'
      preLoaderRoute: typeof SignalAdjustmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/machines': {
      id: '/machines'
      path: '/machines'
      fullPath: '/machines'
      preLoaderRoute: typeof MachinesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auto-hmi': {
      id: '/auto-hmi'
      path: '/auto-hmi'
      fullPath: '/auto-hmi'
      preLoaderRoute: typeof AutoHmiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alerts': {
      id: '/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof AlertsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AlertsRoute: AlertsRoute,
  AnalyticsRoute: AnalyticsRoute,
  AutoHmiRoute: AutoHmiRoute,
  LoginRoute: LoginRoute,
  MachinesRoute: MachinesRoute,
  SettingsRoute: SettingsRoute,
  SignalAdjustmentRoute: SignalAdjustmentRoute,
  SystemMonitoringRoute: SystemMonitoringRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
